apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: final
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - port: 81
      targetPort: 81
      protocol: TCP

